/*** Copyright (c), The Regents of the University of California            ***
 *** For more information please refer to files in the COPYRIGHT directory ***/
/* rcFileOpen.c - Client API call for fileOpen. Part of the 
 * reoutine may be generated by a script
 */
#include "fileOpen.h"

int
rcFileOpen (rcComm_t *conn, fileOpenInp_t *fileOpenInp)
{
    int status;

    status = procApiRequest (conn, FILE_OPEN_AN, fileOpenInp, NULL,
      (void **) NULL, NULL);

    return (status);
}

