/*** Copyright (c), The Regents of the University of California            ***
 *** For more information please refer to files in the COPYRIGHT directory ***/
/* dataObjRsync.h - This dataObj may be generated by a program or script
 */

#ifndef DATA_OBJ_RSYNC_H
#define DATA_OBJ_RSYNC_H

/* This is a Object File I/O API call */

#include "rods.h"
#include "rcMisc.h"
#include "procApiRequest.h"
#include "apiNumber.h"
#include "initServer.h"
#include "dataObjWrite.h"
#include "dataObjClose.h"

#if defined(RODS_SERVER)
#define RS_DATA_OBJ_RSYNC rsDataObjRsync
/* prototype for the server handler */
int
rsDataObjRsync (rsComm_t *rsComm, dataObjInp_t *dataObjInp,
msParamArray_t **outParamArray); 
int
rsRsyncDataToFile (rsComm_t *rsComm, dataObjInp_t *dataObjInp);
int
rsRsyncFileToData (rsComm_t *rsComm, dataObjInp_t *dataObjInp);
int
rsRsyncDataToData (rsComm_t *rsComm, dataObjInp_t *dataObjInp);
int
_rsDataObjChksum (rsComm_t *rsComm, dataObjInp_t *dataObjInp, 
char **outChksumStr, dataObjInfo_t **dataObjInfoHead);
#else
#define RS_DATA_OBJ_RSYNC NULL
#endif

#ifdef  __cplusplus
extern "C" {
#endif

/* prototype for the client call */
int
rcDataObjRsync (rcComm_t *conn, dataObjInp_t *dataObjInp); 

#ifdef  __cplusplus
}
#endif

#endif	/* DATA_OBJ_RSYNC_H */
