/*** Copyright (c), The Regents of the University of California            ***
 *** For more information please refer to files in the COPYRIGHT directory ***/
/* dataObjGet.h - This dataObj may be generated by a program or script
 */

#ifndef DATA_OBJ_GET_H
#define DATA_OBJ_GET_H

/* This is a high level type API call */

#include "rods.h"
#include "rcMisc.h"
#include "procApiRequest.h"
#include "apiNumber.h"
#include "initServer.h"
#include "dataObjWrite.h"
#include "dataObjClose.h"

#if defined(RODS_SERVER)
#define RS_DATA_OBJ_GET rsDataObjGet
/* prototype for the server handler */
int
rsDataObjGet (rsComm_t *rsComm, dataObjInp_t *dataObjInp, 
portalOprOut_t **portalOprOut, bytesBuf_t *dataObjOutBBuf);
int
_rsDataObjGet (rsComm_t *rsComm, dataObjInp_t *dataObjInp,
portalOprOut_t **portalOprOut, bytesBuf_t *dataObjOutBBuf, int handlerFlag);
int
l2DataObjGet (rsComm_t *rsComm, int l1descInx, 
portalOprOut_t **portalOprOut);
int
l3DataGetSingleBuf (rsComm_t *rsComm, int l1descInx, 
bytesBuf_t *dataObjOutBBuf, portalOprOut_t **portalOprOut);
int
l3FileGetSingleBuf (rsComm_t *rsComm, int l1descInx,  
bytesBuf_t *dataObjOutBBuf);
#else
#define RS_DATA_OBJ_GET NULL
#endif

#ifdef  __cplusplus
extern "C" {
#endif

/* prototype for the client call */
int
rcDataObjGet (rcComm_t *conn, dataObjInp_t *dataObjInp, char *locFilePath);

#ifdef  __cplusplus
}
#endif

#endif	/* DATA_OBJ_GET_H */
