/*** Copyright (c), The Regents of the University of California            ***
 *** For more information please refer to files in the COPYRIGHT directory ***/
/* dataObjPut.h - This dataObj may be generated by a program or script
 */

#ifndef DATA_OBJ_PUT_H
#define DATA_OBJ_PUT_H

/* This is a high level type API call */

#include "rods.h"
#include "rcMisc.h"
#include "procApiRequest.h"
#include "apiNumber.h"
#include "initServer.h"
#include "dataObjWrite.h"
#include "dataObjClose.h"

#if defined(RODS_SERVER)
#define RS_DATA_OBJ_PUT rsDataObjPut
/* prototype for the server handler */
int
rsDataObjPut (rsComm_t *rsComm, dataObjInp_t *dataObjInp, 
bytesBuf_t *dataObjInpBBuf, portalOprOut_t **portalOprOut);
int
_rsDataObjPut (rsComm_t *rsComm, dataObjInp_t *dataObjInp,
bytesBuf_t *dataObjInpBBuf, portalOprOut_t **portalOprOut, int handlerFlag);
int
l2DataObjPut (rsComm_t *rsComm, int l1descInx, 
portalOprOut_t **portalOprOut);
int
l3DataPutSingleBuf (rsComm_t *rsComm, dataObjInp_t *dataObjInp,
bytesBuf_t *dataObjInpBBuf);
int
l3FilePutSingleBuf (rsComm_t *rsComm, int l1descInx, bytesBuf_t *dataObjInpBBuf);
#else
#define RS_DATA_OBJ_PUT NULL
#endif

#ifdef  __cplusplus
extern "C" {
#endif

/* prototype for the client call */
int
rcDataObjPut (rcComm_t *conn, dataObjInp_t *dataObjInp,
char *locFilePath);

#ifdef  __cplusplus
}
#endif

#endif	/* DATA_OBJ_PUT_H */
