/*** Copyright (c), The Regents of the University of California            ***
 *** For more information please refer to files in the RENAMERIGHT directory ***/
/* dataObjRename.h - This dataObj may be generated by a program or script
 */

#ifndef DATA_OBJ_RENAME_H
#define DATA_OBJ_RENAME_H

/* This is a Object File I/O API call */

#include "rods.h"
#include "procApiRequest.h"
#include "apiNumber.h"
#include "dataObjCopy.h"

#ifdef  __cplusplus
extern "C" {
#endif

#if defined(RODS_SERVER)
#define RS_DATA_OBJ_RENAME rsDataObjRename
/* prototype for the server handler */
int
rsDataObjRename (rsComm_t *rsComm, dataObjCopyInp_t *dataObjRenameInp);
int
_rsDataObjRename (rsComm_t *rsComm, dataObjCopyInp_t *dataObjRenameInp);
int
specCollObjRename (rsComm_t *rsComm, dataObjInfo_t *srcDataObjInfo,
dataObjInfo_t *destDataObjInfo);
int
l3Rename (rsComm_t *rsComm, dataObjInfo_t *dataObjInfo, char *newFileName);
#else
#define RS_DATA_OBJ_RENAME NULL
#endif

/* prototype for the client call */
int
rcDataObjRename (rcComm_t *conn, dataObjCopyInp_t *dataObjRenameInp);

#ifdef  __cplusplus
}
#endif

#endif	/* DATA_OBJ_RENAME_H */
