/*** Copyright (c), The Regents of the University of California            ***
 *** For more information please refer to files in the COPYRIGHT directory ***/
/* dataObjCopy.h - This dataObj may be generated by a program or script
 */

#ifndef DATA_OBJ_COPY_H
#define DATA_OBJ_COPY_H

/* This is a high level type API call */

#include "rods.h"
#include "procApiRequest.h"
#include "apiNumber.h"

typedef struct {
    dataObjInp_t srcDataObjInp;
    dataObjInp_t destDataObjInp;
} dataObjCopyInp_t;

#define DataObjCopyInp_PI "struct DataObjInp_PI; struct DataObjInp_PI;"

#if defined(RODS_SERVER)
#define RS_DATA_OBJ_COPY rsDataObjCopy
/* prototype for the server handler */
int
rsDataObjCopy (rsComm_t *rsComm, dataObjCopyInp_t *dataObjCopyInp,
transStat_t **transStat);
int
_rsDataObjCopy (rsComm_t *rsComm, int destL1descInx, int existFlag);
#else
#define RS_DATA_OBJ_COPY NULL
#endif

#ifdef  __cplusplus
extern "C" {
#endif

/* prototype for the client call */
int
rcDataObjCopy (rcComm_t *conn, dataObjCopyInp_t *dataObjCopyInp);
int
clearDataObjCopyInp (dataObjCopyInp_t *dataObjCopyInp);
#ifdef  __cplusplus
}
#endif

#endif	/* DATA_OBJ_COPY_H */
