/*** Copyright (c), The Regents of the University of California            ***
 *** For more information please refer to files in the COPYRIGHT directory ***/
/* fileLseek.h - This file may be generated by a program or script
 */

#ifndef FILE_LSEEK_H
#define FILE_LSEEK_H

/* This is a low level file type API call */

#include "rods.h"
#include "rcMisc.h"
#include "procApiRequest.h"
#include "apiNumber.h"
#include "initServer.h"

#include "fileDriver.h"

typedef struct {
    int fileInx;
    rodsLong_t offset; 
    int whence;
} fileLseekInp_t;
    
typedef struct {
    rodsLong_t offset; 
} fileLseekOut_t;

#define fileLseekInp_PI "int fileInx; double offset; int whence;"

#define fileLseekOut_PI "double offset;"

#if defined(RODS_SERVER)
#define RS_FILE_LSEEK rsFileLseek
/* prototype for the server handler */
int
rsFileLseek (rsComm_t *rsComm, fileLseekInp_t *fileLseekInp, 
fileLseekOut_t **fileLseekOut);
int
_rsFileLseek (rsComm_t *rsComm, fileLseekInp_t *fileLseekInp, 
fileLseekOut_t **fileLseekOut);
int
remoteFileLseek (rsComm_t *rsComm, fileLseekInp_t *fileLseekInp,
fileLseekOut_t **fileLseekOut, rodsServerHost_t *rodsServerHost);
#else
#define RS_FILE_LSEEK NULL
#endif

/* prototype for the client call */
int
rcFileLseek (rcComm_t *conn, fileLseekInp_t *fileLseekInp,
fileLseekOut_t **fileLseekOut);

#endif	/* FILE_LSEEK_H */
