/*** Copyright (c), The Regents of the University of California            ***
 *** For more information please refer to files in the COPYRIGHT directory ***/
/* structFileExtAndReg.h - This file may be generated by a program or 
 * script
 */

#ifndef GET_RESC_QUOTA_H
#define GET_RESC_QUOTA_H

/* This is a Object File I/O call */

#include "rods.h"
#include "rcMisc.h"
#include "procApiRequest.h"
#include "apiNumber.h"
#include "initServer.h"
#include "icatDefines.h"

#include "rodsGenQuery.h"  /* for input/output structs, etc */


typedef struct getRescQuotaInp {
    char rescName[NAME_LEN];		/* resc or rescGrp Name */
    char userName[NAME_LEN];		/* userName or userName#zone */
    char zoneHint[MAX_NAME_LEN];
    int flags;				/* not used */
    int dummy;
    keyValPair_t condInput;   /* include chksum flag and value */
} getRescQuotaInp_t;

typedef struct rescQuota {
    char rescName[NAME_LEN];            /* resc Name */
    char rescGrpName[NAME_LEN];         /* rescGrp Name */
    int flag;				/* not used */
    int dummy;
    rodsLong_t quotaLimit;
    rodsLong_t quotaOverrun;
    struct rescQuota *next;
} rescQuota_t;

#define getRescQuotaInp_PI "str rescName[NAME_LEN]; str userName[NAME_LEN]; str zoneHint[MAX_NAME_LEN]; int int flags; int dummy; struct KeyValPair_PI;"

#define rescQuota_PI "str rescName[NAME_LEN]; str userName[NAME_LEN]; str rescGrpName[NAME_LEN]; int int flags; int dummy; struct *rescQuota_PI;"

#if defined(RODS_SERVER)
#define RS_GET_RESC_QUOTA rsGetRescQuota
/* prototype for the server handler */
int
rsGetRescQuota (rsComm_t *rsComm, getRescQuotaInp_t *getRescQuotaInp,
rescQuota_t **rescQuota);
int
_rsGetRescQuota (rsComm_t *rsComm, getRescQuotaInp_t *getRescQuotaInp,
rescQuota_t **rescQuota);
int
setRescQuota (rsComm_t *rsComm, char *zoneHint, rescGrpInfo_t **myRescGrpInfo);
int
getQuotaByResc (rsComm_t *rsComm, char *userName, char *rescName,
genQueryOut_t **genQueryOut);
#else
#define RS_GET_RESC_QUOTA NULL
#endif

/* prototype for the client call */
int
rcGetRescQuota (rcComm_t *conn, getRescQuotaInp_t *getRescQuotaInp,
rescQuota_t **rescQuota);

#endif	/* GET_RESC_QUOTA_H */
