/*** Copyright (c), The Regents of the University of California            ***
 *** For more information please refer to files in the COPYRIGHT directory ***/
/* phyBundleColl.h - This file may be generated by a program or 
 * script
 */

#ifndef PHY_BUNDLE_COLL_H
#define PHY_BUNDLE_COLL_H

/* This is a Object File I/O call */

#include "rods.h"
#include "rcMisc.h"
#include "procApiRequest.h"
#include "apiNumber.h"
#include "initServer.h"
#include "structFileExtAndReg.h"

#if defined(RODS_SERVER)
#define RS_PHY_BUNDLE_COLL rsPhyBundleColl
/* prototype for the server handler */
int
rsPhyBundleColl (rsComm_t *rsComm, 
structFileExtAndRegInp_t *phyBundleCollInp);
int
remotePhyBundleColl (rsComm_t *rsComm, 
structFileExtAndRegInp_t *phyBundleCollInp, rodsServerHost_t *rodsServerHost);
int
_rsPhyBundleColl (rsComm_t *rsComm, structFileExtAndRegInp_t *phyBundleCollInp,
rescGrpInfo_t *rescGrpInfo);
int
createPhyBundleDataObj (rsComm_t *rsComm, char *collection,
rescGrpInfo_t *rescGrpInfo, dataObjInp_t *dataObjInp);
int
createPhyBundleDir (rsComm_t *rsComm, dataObjInfo_t *dataObjInfo,
char *outPhyBundleDir);
int
rsMkBundlePath (rsComm_t *rsComm, char *collection, char *outPath,  
int myRanNum);
int
replDataObjForBundle (rsComm_t *rsComm, char *collName, char *dataName,
char *rescName, dataObjInfo_t *outCacheObjInfo);
#else
#define RS_PHY_BUNDLE_COLL NULL
#endif

/* prototype for the client call */
int
rcPhyBundleColl (rcComm_t *conn, 
structFileExtAndRegInp_t *phyBundleCollInp);

#endif	/* PHY_BUNDLE_COLL_H */
