#!/bin/sh -ex

#####################################################################################
#  test2, uses some of the srb commands on srb Objects inside of containers, in order 
#  to see if they are all working according to their design purpose.
#  
#  Unless otherwise stated, all commands with # in front of them, don't seem to be 
#  working properly.
#
#  By: Arcot Rajasekar
#  Modified By: Roman Olschanowsky
#  More modifications to irods: Susan Lindsey
#####################################################################################

# SDL variables
irodshome=/Users/slinz/iRODS
iDir=$irodshome/clients/icommands/bin

#DATA_FILES="data_1 data_2 data_3 data_4 datadb1.xml dataempty"
DATA_FILES="data_1"
TMP_DIR=TMP
resourceset=`cat ResourcesToTest`

#####################################################################################
#  Make unique names for directories using current date and time
#####################################################################################

if [ "$1" = "" ]
then testid=`date "+%Y%m%d%H%M%S"`
else testid=$1
fi

echo "TESTID = $testid"

$iDir/iinit 
#$iDir/SgetU -d -Y 0

#  Make new test directory in irods space
$iDir/imkdir Itest2Dir$testid
$iDir/icd Itest2Dir$testid
for thisresc in $resourceset ; do
  $iDir/imkdir Isub1
  $iDir/ils -lr
  $iDir/icd Isub1

#####################################################################################
#  Put local data files into newly created container in srb space.
#####################################################################################

  $iDir/Smkcont -S $thisresc Container$testid

  for file in $DATA_FILES ; do
      $iDir/Sput -c Container$testid -S $thisresc $file "$file&COPIES=all" 
  done

  $iDir/icd ..

# Raja doesn't want me to use Srename, he is having problems with it
# So I'll try move  $iDir/Srename -c Container$testid Container.2.$testid

# Doesn't work either  $iDir/Smv Container$testid Container.2.$testid

# Currently we can not move or rename a container

  $iDir/Slscont Container$testid
#takes too long  $iDir/Slscont -l

#####################################################################################
#  Display various information about objects in srb space
#####################################################################################
  $iDir/SgetD  -Y 0 -L 500 "Isub1/*"
  $iDir/ils -lr

#####################################################################################
#  Get all data files from srb space, store them in temp directory, and compare them
#  with another copy of same file to see if they match.
#####################################################################################
  for file in $DATA_FILES ; do
      $iDir/iget Isub1/$file $TMP_DIR/$file.$testid.tmp
      diff $file $TMP_DIR/$file.$testid.tmp
      wc $file $TMP_DIR/$file.$testid.tmp
      rm $TMP_DIR/$file.$testid.tmp
  done

  $iDir/imkdir Isub2g

#####################################################################################
#  Move all files from Sub1 to Sub2
#####################################################################################
  for file in $DATA_FILES ; do
     $iDir/imv Isub1/$file Isub2g
  done

  $iDir/ils -lr
 
#####################################################################################
#  Copy all data across different platforms, then get data to local environment, and
#  compare with local copies of same data.
#####################################################################################

  for store in $resourceset ; do
    $iDir/Smkcont -S $thisresc Container$testid.$store

    for file in $DATA_FILES ; do
       $iDir/icp -c Container$testid.$store -S $store I_sub2/$file Isub1/$file.$store
    done

    $iDir/Ssyncont Container$testid.$store

    $iDir/Sls -lr
#takes too long    $iDir/Slscont 

    for file in $DATA_FILES ; do
      $iDir/Sget Isub1/$file.$store $TMP_DIR/$file.$testid.tmp
      diff $file $TMP_DIR/$file.$testid.tmp
		# add chksum	
      wc $file $TMP_DIR/$file.$testid.tmp
      rm $TMP_DIR/$file.$testid.tmp   
    done

    $iDir/icd Isub1
    $iDir/irm "data*"
    $iDir/irmtrash
    $iDir/icd ..
    $iDir/Srmcont Container$testid.$store
  done

#####################################################################################
#  Do all the clean up, remove data files, directories, and containers
#####################################################################################
  $iDir/irm -r Isub1
  $iDir/irmtrash
  $iDir/Srmcont Container$testid
#  $iDir/Slscont "Container$testid*"
  $iDir/ils -lr
done

#####################################################################################
#  Remove test directory and end session
#####################################################################################
$iDir/icd ..
$iDir/irm Itest2Dir$testid
$iDir/irmtrash
$iDir/iexit
exit 0
