#!/bin/sh

# Usage is:
#	./configure [options]
#
# This shell script configures iRODS based upon user options and
# features of the current platform.
#
if [ ! -f ./bin/runPerlScript ]; then
	echo "Usage error:"
	echo "    Please run this script from the top-level directory"
	echo "    of the iRODS distribution."
	exit 1
fi
./bin/runPerlScript --script install/configure.pl $*
ExitCode="$?"
exit $ExitCode
