#!/bin/sh
#
# Install Postgres for use by iRODS.
#
# Usage is:
#	./installPostgres [options]
#
# This optional shell script automates the process of getting a
# version of Postgres and ODBC source and compiling them for
# use by iRODS.
#
# You do not need this script if you are building Postgres yourself
# or using an existing Postgres installation.
#
# There are no user-editable configuration settings in this file.
#
if [ ! -f ./bin/runPerlScript ]; then
	echo "Usage error:"
	echo "    Please run this script from the top-level directory"
	echo "    of the iRODS distribution."
	exit 1
fi
./bin/runPerlScript --dir install --script installPostgres.pl $*
ExitCode="$?"
exit $ExitCode
