#!/bin/sh
#
# Control iRODS servers.
#
# Usage is:
#	./irodsctl [options]
#
# This shell script starts and stops the iRODS servers.
#
IRODS_HOME=""

$IRODS_HOME/bin/runPerlScript --dir $IRODS_HOME --script $IRODS_HOME/bin/irodsctl.pl $*
ExitCode="$?"
exit $ExitCode
