/* stockQuoteMS_wsdl.h
   Generated by wsdl2h 1.2.9l from stockQuote.wsdl and typemap.dat
   2007-10-09 21:48:15 GMT
   Copyright (C) 2001-2007 Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL or Genivia's license for commercial use.
*/

/* NOTE:

 - Compile this file with soapcpp2 to complete the code generation process.
 - Use soapcpp2 option -I to specify paths for #import
   To build with STL, 'stlvector.h' is imported from 'import' dir in package.
 - Use wsdl2h options -c and -s to generate pure C code or C++ code without STL.
 - Use 'typemap.dat' to control schema namespace bindings and type mappings.
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Use Doxygen (www.doxygen.org) to browse this file.
 - Use wsdl2h option -l to view the software license terms.

   DO NOT include this file directly into your project.
   Include only the soapcpp2-generated headers and source code files.
*/

//gsoapopt cw

/******************************************************************************\
 *                                                                            *
 * http://www.webserviceX.NET/                                                *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/


/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to typemap.dat to rerun wsdl2h:

ns1 = "http://www.webserviceX.NET/"

*/

//gsoap ns1   schema namespace:	http://www.webserviceX.NET/
//gsoap ns1   schema elementForm:	qualified
//gsoap ns1   schema attributeForm:	unqualified

/******************************************************************************\
 *                                                                            *
 * Schema Types                                                               *
 *                                                                            *
\******************************************************************************/




/// Element "http://www.webserviceX.NET/":GetQuote of complexType.

/// "http://www.webserviceX.NET/":GetQuote is a complexType.
struct _ns1__GetQuote
{
/// Element symbol of type xs:string.
    char*                                symbol                         0;	///< Optional element.
};


/// Element "http://www.webserviceX.NET/":GetQuoteResponse of complexType.

/// "http://www.webserviceX.NET/":GetQuoteResponse is a complexType.
struct _ns1__GetQuoteResponse
{
/// Element GetQuoteResult of type xs:string.
    char*                                GetQuoteResult                 0;	///< Optional element.
};

/// Element "http://www.webserviceX.NET/":string of type xs:string.
/// Note: use wsdl2h option -g to generate this global element declaration.

/******************************************************************************\
 *                                                                            *
 * Services                                                                   *
 *                                                                            *
\******************************************************************************/


//gsoap ns1  service name:	StockQuoteSoap 
//gsoap ns1  service type:	StockQuoteSoap 
//gsoap ns1  service port:	http://www.webservicex.net/stockquote.asmx 
//gsoap ns1  service namespace:	http://www.webserviceX.NET/ 
//gsoap ns1  service transport:	http://schemas.xmlsoap.org/soap/http 

/** @mainpage Service Definitions

@section Service_bindings Bindings
  - @ref StockQuoteSoap

*/

/**

@page StockQuoteSoap Binding "StockQuoteSoap"

@section StockQuoteSoap_operations Operations of Binding  "StockQuoteSoap"
  - @ref __ns1__GetQuote

@section StockQuoteSoap_ports Endpoints of Binding  "StockQuoteSoap"
  - http://www.webservicex.net/stockquote.asmx

Note: use wsdl2h option -N to change the service binding prefix name

*/

/******************************************************************************\
 *                                                                            *
 * StockQuoteSoap                                                             *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * __ns1__GetQuote                                                            *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns1__GetQuote" of service binding "StockQuoteSoap"

/**

Operation details:

Get Stock quote for a company Symbol
  - SOAP document/literal style
  - SOAP action="http://www.webserviceX.NET/GetQuote"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__GetQuote(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    struct _ns1__GetQuote*              ns1__GetQuote,
    // response parameters:
    struct _ns1__GetQuoteResponse*      ns1__GetQuoteResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__GetQuote(
    struct soap *soap,
    // request parameters:
    struct _ns1__GetQuote*              ns1__GetQuote,
    // response parameters:
    struct _ns1__GetQuoteResponse*      ns1__GetQuoteResponse
  );
@endcode

*/

//gsoap ns1  service method-style:	GetQuote document
//gsoap ns1  service method-encoding:	GetQuote literal
//gsoap ns1  service method-action:	GetQuote http://www.webserviceX.NET/GetQuote
int __ns1__GetQuote(
    struct _ns1__GetQuote*              ns1__GetQuote,	///< Request parameter
    struct _ns1__GetQuoteResponse*      ns1__GetQuoteResponse	///< Response parameter
);

/* End of stockQuoteMS_wsdl.h */
